package com.ashivrina.tests;

import com.ashivrina.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @DisplayName("Check https://it.innoscripta.com/ main page")
    void mainPageTest() {
        step("Open https://it.innoscripta.com/", () -> {
            open("https://it.innoscripta.com/");
        });

        step("Check there's the 'Apply now' button in header", () -> {
            $(".header__btn").shouldHave(text("Apply now"));
        });

        step("Check the header text", () -> {
            $(".h3").shouldHave(text("Join our star-team today"));
        });

        step("Check subheader text", () -> {
            $(".section-first__main").shouldHave(text("innoscripta"));
        });
    }

    @Test
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://it.innoscripta.com/'", () ->
            open("https://it.innoscripta.com/"));

        step("Page title should have text 'innoscripta HR'", () -> {
            String expectedTitle = "innoscripta HR";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://it.innoscripta.com/'", () ->
            open("https://it.innoscripta.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}